name: Upload PySpark Job to GCS

on:
  push:
    branches:
      - stage
      - main
  workflow_dispatch:
    
jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set ENV
        id: set-env
        run: |
          echo "⚙️ GITHUB_REF: $GITHUB_REF"
          echo "⚙️ Branch name extracted: ${GITHUB_REF##*/}"
          if [[ "${GITHUB_REF##*/}" == "stage" ]]; then
            echo "ENV=stg" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo  "ENV=prod" >> $GITHUB_ENV
          else
            echo "Unknown branch"
            exit 1
            fi

      - name: Set dynamic secrets
        id: secrets
        run: |
          echo "GCP_PROJECT=${{ secrets['GCP_PROJECT_' + env.ENV | upper] }}" >> $GITHUB_ENV
          echo "GCS_BUCKET=${{ secrets['GCS_BUCKET_' + env.ENV | upper] }}" >> $GITHUB_ENV
        shell: bash

      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ secrets['GCP_SA_KEY_' + env.ENV | upper] }}
          export_default_credentials: true

      - name: Upload Pyspark Job and dependencies to GCS
        run: |
          gsutil -m cp scripts/sqlserver_to_bq.py gs://${{ env.GCS_BUCKET }}/pyspark/
          gsutil -m cp -r scripts/dependencies gs://${{ env.GCS_BUCKET }}/pyspark/