name: Upload PySpark Job to GCS

on:
  push:
    branches:
      - stage
      - main
  workflow_dispatch:

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set ENV
        id: set-env
        run: |
          echo "⚙️ GITHUB_REF: $GITHUB_REF"
          echo "⚙️ Branch name extracted: ${GITHUB_REF##*/}"
          if [[ "${GITHUB_REF##*/}" == "stage" ]]; then
            echo "ENV=STG" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "ENV=PROD" >> $GITHUB_ENV
          else
            echo "❌ Unknown branch"
            exit 1
          fi

      - name: Export dynamic secrets to ENV
        run: |
          echo "GCP_PROJECT=${{ secrets.GCP_PROJECT_STG }}" >> $GITHUB_ENV
          echo "GCS_BUCKET=${{ secrets.GCS_BUCKET_STG }}" >> $GITHUB_ENV

        if: env.ENV == 'STG'

      - name: Export dynamic secrets to ENV
        run: |
          echo "GCP_PROJECT=${{ secrets.GCP_PROJECT_PROD }}" >> $GITHUB_ENV
          echo "GCS_BUCKET=${{ secrets.GCS_BUCKET_PROD }}" >> $GITHUB_ENV

        if: env.ENV == 'PROD'

      - name: Authenticate to GCP (STG)
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_STG }}
        if: env.ENV == 'STG'

      - name: Authenticate to GCP (PROD)
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROD }}
        if: env.ENV == 'PROD'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Check if dependencies changed
        id: deps-changed
        run: |
          git fetch origin ${{ github.event.before }}
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "🔍 Changed files: $changed_files"
          if echo "$changed_files" | grep -qE 'mssql_to_bq/scripts/dependencies/(logging|spark)\.py'; then
            echo "zip_needed=true" >> $GITHUB_ENV
          else
            echo "zip_needed=false" >> $GITHUB_ENV

      - name: Zip dependencies
        if: env.zip_needed == 'true'
        run: |
          echo "📦 Creating dependencies.zip..."
          cd mssql_to_bq/scripts
          zip -r dependencies.zip dependencies
          cd -

      - name: Upload PySpark job and zipped dependencies
        run: |
          echo "✅ Uploading to GCS Bucket: $GCS_BUCKET"
          gsutil -m cp mssql_to_bq/scripts/sqlserver_to_bq_job.py gs://${{ env.GCS_BUCKET }}/pyspark/
          if [[ "${{ env.zip_needed }}" == "true" ]]; then
            gsutil cp mssql_to_bq/scripts/dependencies.zip gs://${{ env.GCS_BUCKET }}/pyspark/
          else
            echo "🛑 No changes in dependencies/*.py — skipping zip upload"
          fi

